### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by InfoCopy**

### CODE REVIEW

**Comment by InfoCopy** [comment]
I added a reference to the video.
If you need to load video into Lelylan git repo tell me, I'll send you the video.

**Comment by andreareginato** [comment]
Can you reopen the pull request, otherwise I can't merge it.

**Comment by andreareginato** [comment]
Ok. I managed it :)

**Comment by andreareginato** [comment]
Would be great to add in on youtube and to embed it.
Can you manage with it?

On Wed, Dec 10, 2014 at 4:18 PM, InfoCopy Team Devalopers <
notifications@github.com> wrote:

> I added a reference to the video.
> If you need to load video into Lelylan git repo tell me, I'll send you the
> video.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/lelylan/lab-projects/pull/1#issuecomment-66466502.

## 

Andrea Reginato
Lelylan | reThink your house
http://lelylan.com

**Pull request merged**
